---
- name: kcli crea una maquina
  hosts: localhost
  vars_prompt:
    - name: nombre
      prompt: Elige el nombre de la maquina
      private: false
  tasks:
    
    - name: Comando
      debug:
        msg: " kcli delete vm {{ nombre  }}"
    - name: ejecutando
      ansible.builtin.command: "echo 'yes' | kcli delete vm {{ nombre  }}"
      ignore_errors: true
      register: delete_result
      
      
