---
- name: kcli crea una maquina
  hosts: localhost
  vars_prompt:
    - name: nombre
      prompt: Elige el nombre de la maquina o maquinas
      private: false
  tasks:
    
    - name: Comando
      debug:
        msg: " kcli delete vm {{ nombre  }}"
    - name: ejecutando
      ansible.builtin.command: "kcli stop vm {{ nombre  }}"
      
      
